[constants]
#avr_prefix = '/opt/avr-gcc'
avr_toolchain_bin = avr_prefix / 'bin'
avr_toolchain_prefix = avr_toolchain_bin / 'avr-'
avr_specs = avr_prefix / 'lib/gcc/avr/15.1.0/device-specs/specs-atmega328p'
f_cpu = '16000000L'

mcu_args = [
    '-mmcu=atmega328p',
    '-specs=' + avr_specs,
    '-DF_CPU=' + f_cpu]

compile_args = [
    '-fno-permissive',
    '-ffunction-sections',
    '-fdata-sections']

[binaries]
c = ['ccache', avr_toolchain_prefix + 'gcc']

cpp = ['ccache', avr_toolchain_prefix + 'g++']

#ar = avr_toolchain_prefix + 'ar'
ranlib = avr_toolchain_prefix + 'ranlib'
strip = avr_toolchain_prefix + 'strip'

[built-in options]
cpp_args = mcu_args + compile_args + ['-fno-threadsafe-statics']
c_args = mcu_args + compile_args
cpp_link_args = mcu_args + ['-Wl,--gc-sections', '-Wl,-e,main']
b_lto = true
b_staticpic = false
#b_eh=false
#b_rtti=false

[host_machine]
system = 'avr'
cpu_family = 'avr'
cpu = 'avr'
endian = 'little'

[properties]
variant = 'standard'
avr_toolchain_bin_path = avr_toolchain_bin
