name: Cross compile for Atmega328p
permissions: read-all

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - name: Fetch sources
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: pip

    - name: Install native gcc toolchain
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: build-essential
        version: 1  # bump to invalidate cache

    - name: Cache AVR-GCC toolchain
      id: avr-cache
      uses: actions/cache@v3
      with:
        path: /opt/avr-gcc
        key: avr-gcc

    - name: Install AVR-GCC 14.2 from Microchip
      if: steps.avr-cache.outputs.cache-hit != 'true'
      run: |
        wget https://ww1.microchip.com/downloads/aemDocuments/documents/DEV/ProductDocuments/SoftwareTools/avr8-gnu-toolchain-4.0.0.52-linux.any.x86_64.tar.gz
        tar -xzf avr8-gnu-toolchain-4.0.0.52-linux.any.x86_64.tar.gz
        sudo mv avr8-gnu-toolchain-linux_x86_64 /opt/avr-gcc

    - name: Install Python dependencies
      run: |
        pip install --upgrade uv
        uv pip install --system meson ninja parsimonious

    - name: Cache 3rd party C++ projects
      uses: actions/cache@v3
      with:
        key: meson-cache
        path: subprojects/packagecache/

    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ccache-avr

    - name: Resolve C++ build dependencies
      run: >-
        meson setup
        --buildtype=release
        --cross-file=avr-cross-ubuntu2404.ini
        --cross-file=avr-cross.ini
        build-avr/

    - name: Build the blinky app with Arduino HAL layer
      run: ninja -C build-avr examples/blinky/blinky

    - name: Build example binary_custom
      run: ninja -C build-avr examples/log/binary_custom/binary_custom
