name: Cross compile for Atmel328p

on:
  workflow_dispatch:

  push:
    branches-ignore:
      - logging-writer

jobs:
  build:

    runs-on: ubuntu-25.10
    steps:
    - name: Fetch sources
      uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: pip

    - name: Install avr-gcc toolchain
      uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: build-essential avr-gcc
        version: 1  # bump to invalidate cache

    - name: Install Python dependencies
      run: |
        pip install --upgrade uv
        uv pip install --system meson ninja

    - name: Cache 3rd party C++ projects
      uses: actions/cache@v3
      with:
        key: meson-cache
        path: subprojects/packagecache/

    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ccache-avr

    - name: Resolve C++ build dependencies
      run: >-
        meson setup
        --buildtype=release
        --cross-file=avr-cross-archlinux.ini
        build-avr/

    - name: Build the blinky app with Arduino HAL layer
      run: ninja -C build-avr examples/blinky/blinky

    - name: Build example binary_custom
      run: ninja -C build-avr examples/log/binary_custom/binary_custom

